#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}

// config server
$preparing = [
    'redis' => [
        'scheme'     => 'tcp',
        'host'       => '127.0.0.1',
        'port'       => 6379,
        'persistent' => true,
    ],
    'server' => [
        'address' => "0.0.0.0",
        'port'    => 9501,
    ],
];

// initialize server
$app = new Symfony\Component\Console\Application('Tiny Suggest server', '0.1.0');
$app->add(new Tiny\Command\Start);
$app->add(new Tiny\Command\Stop);
$app->add(new Tiny\Command\Server($preparing));

$app->run();
