#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}

// config server
$preparing = [
    'redis' => [
        'scheme'     => 'tcp',
        'host'       => '127.0.0.1',
        'port'       => 6379,
        'persistent' => true,
        'database'   => 15,
    ],
    'server' => [
        'address' => "0.0.0.0",
        'port'    => 9501,
    ],
    'suggest' => [
        "cn_include_pinyin" => false
    ]
];


// there has start config
$configFile = './config.json';
if(file_exists($configFile)) {
    $content = file_get_contents($configFile);

    $preparing = json_decode($content, true);
}


// initialize server
$app = new Symfony\Component\Console\Application('Tiny Suggest server', '0.1.0');

// Before running check
if (!extension_loaded('swoole'))
{
    echo 'Swoole lib has\'t installed' . "\n";
    exit();
}

$app->add(new Tiny\Command\Start);
$app->add(new Tiny\Command\Stop);
$app->add(new Tiny\Command\Server($preparing));

$app->run();
